SERVER_A = ("stun.l.google.com", 19302)
SERVER_B = ("stun1.l.google.com", 19302)
STUN_SERVER_PORT = 3478
PARAMETERS_PATH = "parameters.pem"
SIGNALING_SERVER_IP_MAIN_SERVER = "192.168.1.119"
SIGNALING_SERVER_IP_MAIN_CLIENT = "80.178.219.125"
SIGNALING_SERVER_PORT = 12347
IP_ADDRESS_ALLOWLISTING = "0.0.0.0"
DH_START = "DHK"
DH_MSG = "DHK|OK"
ROOM_REQUEST = "ROOM|"
IP_PORT_EXT_MSG = "IPE"
DELIMITER = "|"
group_x25519 = b"\x00\x1d"

TLS_AES_128_GCM_SHA256 = b"\x13\x01"
TLS_AES_256_GCM_SHA384 = b"\x13\x02"

SERVER_HELLO_TYPE_INT = 2
HANDSHAKE_MSG_ENCRYPTED_EXTENSIONS = 1
HANDSHAKE_MSG_SERVER_HELLO = 0
HANDSHAKE_MSG_CLIENT_HELLO = 0

DEMO_HEADER = b"\x11\x22\x33\x44\x55"
SERVER_HELLO_PACKET = "server_hello_packet"
HANDSHAKE_TYPE = b"\x16"
HEADER_INFO = b"\xe2"
ENCRYPTED_EXTENSIONS_TYPE = b"\x08"
CERTIFICATE_TYPE = b"\x0b"
CERT_VERIFY_TYPE = b"\x0f"
HEADER_INFO_INT = 46

PATH_STORE_PRIVATE_KEY = "C:\\School_11_Grade\\WebRTC\\key_private.pem"
PATH_STORE_PUBLIC_KEY = "C:\\School_11_Grade\\WebRTC\\key_public.pem"
PATH_TO_STORE_CERTIFICATE = "C:\\School_11_Grade\\WebRTC\\certificate.pem"

DELIMITER_BYTES = b"|"
